INSERT INTO product VALUES (1, 'Chocolate')
INSERT INTO product VALUES (2, 'Coffee')

INSERT INTO purchase (product, price) VALUES (1, 5)
INSERT INTO purchase (product, price) VALUES (1, 5)
INSERT INTO purchase (product, price) VALUES (2, 3)
INSERT INTO purchase (product, price) VALUES (1, 5)
INSERT INTO purchase (product, price) VALUES (2, 5)
INSERT INTO purchase (product, price) VALUES (1, 5)
INSERT INTO purchase (product, price) VALUES (1, 5)
INSERT INTO purchase (product, price) VALUES (2, 3)
INSERT INTO purchase (product, price) VALUES (1, 5)
INSERT INTO purchase (product, price) VALUES (1, 5)